name: Export Telegram Feed
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install telethon

      - name: Export chat -> public/telegram-feed.json
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_SESSION_STRING: ${{ secrets.TG_SESSION_STRING }}
          TG_CHAT: ${{ secrets.TG_CHAT }}
          LIMIT: ${{ secrets.LIMIT }}
        run: python scripts/export_chat.py

      - name: Commit & push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/telegram-feed.json
          git commit -m "Update telegram-feed.json" || echo "No changes"
          git push